### ISSUE TITLE
Warn about uglifyjs new `directives` option

### ISSUE THREAD

**Issue by risq** [wanadev/abitbol#18]
Since uglifyjs v3.4.3, `directives` option (true by default) remove non standard directives which breaks abitbol annotations

https://github.com/mishoo/UglifyJS2/pull/3203
https://github.com/mishoo/UglifyJS2/issues/3166
https://github.com/mishoo/UglifyJS2/commit/76df77c08c684bc49bebb35d6d527d90cea48108

**Comment by flozz** [comment]
A warning was added in the doc :)
